### ISSUE TITLE
On window resize, canvas coordinates are off. Need to recalculate 

### ISSUE THREAD

**Issue by mneira10** [Virtuai/podoscope#1]

**Comment by dnarvaez27** [comment]
We are using native APIs for getting the user pointer. We'll work on that as soon as we figure out, why this happens.

Here's the preview of the code of the coordinates of the pointer
```
  // CamCanvas.jsx
  mouseClickHandler(e) {
    const x = e.nativeEvent.offsetX;
    const y = e.nativeEvent.offsetY;
    ...
```

**Comment by mneira10** [comment]
Program is meant to stay full screen under the contract requirements.
